/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WithdrawRouteImport } from './routes/withdraw'
import { Route as RepayRouteImport } from './routes/repay'
import { Route as LiquidateRouteImport } from './routes/liquidate'
import { Route as DepositRouteImport } from './routes/deposit'
import { Route as BorrowRouteImport } from './routes/borrow'
import { Route as IndexRouteImport } from './routes/index'

const WithdrawRoute = WithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const RepayRoute = RepayRouteImport.update({
  id: '/repay',
  path: '/repay',
  getParentRoute: () => rootRouteImport,
} as any)
const LiquidateRoute = LiquidateRouteImport.update({
  id: '/liquidate',
  path: '/liquidate',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositRoute = DepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => rootRouteImport,
} as any)
const BorrowRoute = BorrowRouteImport.update({
  id: '/borrow',
  path: '/borrow',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/borrow': typeof BorrowRoute
  '/deposit': typeof DepositRoute
  '/liquidate': typeof LiquidateRoute
  '/repay': typeof RepayRoute
  '/withdraw': typeof WithdrawRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/borrow': typeof BorrowRoute
  '/deposit': typeof DepositRoute
  '/liquidate': typeof LiquidateRoute
  '/repay': typeof RepayRoute
  '/withdraw': typeof WithdrawRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/borrow': typeof BorrowRoute
  '/deposit': typeof DepositRoute
  '/liquidate': typeof LiquidateRoute
  '/repay': typeof RepayRoute
  '/withdraw': typeof WithdrawRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/borrow'
    | '/deposit'
    | '/liquidate'
    | '/repay'
    | '/withdraw'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/borrow' | '/deposit' | '/liquidate' | '/repay' | '/withdraw'
  id:
    | '__root__'
    | '/'
    | '/borrow'
    | '/deposit'
    | '/liquidate'
    | '/repay'
    | '/withdraw'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BorrowRoute: typeof BorrowRoute
  DepositRoute: typeof DepositRoute
  LiquidateRoute: typeof LiquidateRoute
  RepayRoute: typeof RepayRoute
  WithdrawRoute: typeof WithdrawRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/withdraw': {
      id: '/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof WithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repay': {
      id: '/repay'
      path: '/repay'
      fullPath: '/repay'
      preLoaderRoute: typeof RepayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liquidate': {
      id: '/liquidate'
      path: '/liquidate'
      fullPath: '/liquidate'
      preLoaderRoute: typeof LiquidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposit': {
      id: '/deposit'
      path: '/deposit'
      fullPath: '/deposit'
      preLoaderRoute: typeof DepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/borrow': {
      id: '/borrow'
      path: '/borrow'
      fullPath: '/borrow'
      preLoaderRoute: typeof BorrowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BorrowRoute: BorrowRoute,
  DepositRoute: DepositRoute,
  LiquidateRoute: LiquidateRoute,
  RepayRoute: RepayRoute,
  WithdrawRoute: WithdrawRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
