# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.1.7
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: me@derekscruggs.com
author_name: Derek Scruggs
contract_name: exod_tools
preset_name: starter
project_name: exod-tools

